const style = {
  containerBoxSideBar: (isCollapsed:boolean) => ({
    bgcolor: "",
    display: "flex",
    width: isCollapsed ? "70px" : "265px",
    flexDirection: "column",
    height: "100vh",
    justifyContent: "space-between",
    borderRight: "1px solid  #E5E5E5",
    transition: 'width 0.3s ease-in-out',
  }),
  containerBoxSideBarTop: {
    bgcolor: "",
    display: "flex",
    flexDirection: "column",
    //   justifyContent: "space-between",
    gap: "20px",
  },
  logoTypo: {
    display: "flex",
    // alignItems: "center",
    justifyContent: "",
    gap: "12px",
    fontSize: "24px",
    fontWeight: 700,
    lineHeight: "33px",
    padding: "12px 16px",
    bgcolor:"",
    transition: 'width 0.3s ease-in-out'
  },
  collapseTypo: {
    bgcolor: "",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: "#676E85",
    //   fontSize: "24px",
    fontWeight: 500,
    lineHeight: "23px",
    padding: "12px 16px",
    borderRadius: "12px",
    cursor: "pointer",
    transition: 'width 0.6s ease-in-out',
  },
  menuItemTypo: (isActive:boolean) => ({
    cursor: "pointer",
    padding: "12px 16px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: isActive ? "#E6ECFF" : "",
    color: isActive ? "#4950FF" : "",
    fontWeight: isActive ? 600 : 500,
    lineHeight: "24px",
    borderRadius: "12px",
  }),
};

export default style;
