const style = {
  containerBoxSideBar: (isCollapsed:boolean) => ({
    display: "flex",
    width: isCollapsed ? "70px" : "265px",
    flexDirection: "column",
    height: "100vh",
    justifyContent: "space-between",
    borderRight: "1px solid  #E5E5E5",
    transition: 'width 0.3s ease-in-out',
    paddingTop: '0.5rem',
    boxSizing: 'border-box',
  }),
  containerBoxSideBarTop: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  childTransition: (isCollapsed:boolean) => ({
    display: "flex",
    gap: !isCollapsed ? '12px' : '0px',
    alignItems: 'center',
    py: '12px',
    pl: 'clamp(4px, 2vw, 16px)',
    pr: isCollapsed ? '0px' : 'clamp(4px, 2vw, 16px)',
    transition: 'all 0.6s ease',
    height: '30px'
  }),
  logoTypo: (isCollapsed:boolean) => ({
    fontSize: '24px',
    width: 'auto',
    maxWidth: isCollapsed ? '0%': '100%',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    fontWeight: 700,
    transition: 'all 0.4s linear',
  }),
  childCTransition: (isCollapsed:boolean) => ({
    cursor: "pointer",
    display: "flex",
    width: '100%',
    alignItems: 'center',
    gap: !isCollapsed ? '10px' : '0px',
    py: '12px',
    pl: 'clamp(4px, 2vw, 16px)',
    pr: isCollapsed ? '0px' : 'clamp(4px, 2vw, 16px)',
    transition: 'all 0.4s linear',
  }),
  collapseTypo: (isCollapsed:boolean) => ({
    color: "#676E85",
    fontWeight: 500,
    lineHeight: "23px",
    fontSize: '1rem',
    width: 'auto',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    maxWidth: isCollapsed ? '0%': '100%',
    transition: 'all 0.4s linear',
  }),
  menuItemTypo: (isActive:boolean, isCollapsed:boolean) => ({
    display: "flex",
    alignItems: "center",
    gap: "10px",
    cursor: "pointer",
    py: '12px',
    pl: 'clamp(4px, 2vw, 16px)',
    pr: isCollapsed ? '0px' : 'clamp(4px, 2vw, 16px)',
    background: isActive ? "#E6ECFF" : "",
    borderRadius: "12px",
    transition: 'all 0.4s ease',
  }),
};

export default style;
